name: pr-validation

on:
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3

      - name: Install Deps
        run: yarn install

      - name: Build
        run: yarn build
